import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/provider/queryProvider";

export const metadata: Metadata = {
  title: "Arkadaya Logistic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <QueryProvider>
        <body className="min-h-full flex flex-col">{children}</body>
      </QueryProvider>
    </html>
  );
}
